language: perl
perl:
  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq emboss zlib1g-dev libxml2-dev
  - cpanm -n Devel::Cover::Report::Coveralls
  - ./build/ci/run_build.sh

script: perl Makefile.PL && make && cover -test -report coveralls

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master
#    - topic/add_search_terms
