language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq emboss hmmer

script: perl Makefile.PL && make && make test

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master